<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ICT Monthly Complaint Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            margin: 0;
            padding: 30px;
            font-size: 12px;
        }
        /* Header Layout */
        .header {
            border-bottom: 2px solid #2563eb;
            padding-bottom: 10px;
            margin-bottom: 20px;
            width: 100%;
        }
        table.header-table { width: 100%; border: none; }
        table.header-table td { border: none; padding: 0; vertical-align: bottom; }
        .header h1 { margin: 0; color: #1e293b; font-size: 24px; }
        .meta-data { color: #64748b; font-size: 12px; margin-top: 5px; }

        /* Summary Cards (Crisp HTML Text) */
        table.summary-container {
            width: 100%;
            margin-bottom: 20px;
            border-spacing: 10px; /* Creates gaps between cards */
            border-collapse: separate;
        }
        .summary-card {
            background: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 6px;
            padding: 15px;
            text-align: center;
            width: 20%;
        }
        .summary-card .label { font-weight: bold; color: #64748b; text-transform: uppercase; font-size: 10px; }
        .summary-card .value { font-size: 24px; font-weight: bold; color: #0f172a; margin-top: 5px; }
        .summary-card.open .value { color: #16a34a; }
        .summary-card.assigned .value { color: #2563eb; }
        .summary-card.resolved .value { color: #94a3b8; }

        /* Charts Image Container */
        .charts-container {
            text-align: center;
            background-color: #1a1d24; /* Matches the dark theme of the capture */
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
        }
        .charts-image {
            max-width: 100%;
            height: auto;
            max-height: 300px;
            object-fit: contain;
        }

        /* Detailed Log Table */
        table.data-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        table.data-table th, table.data-table td {
            border: 1px solid #cbd5e1;
            padding: 10px;
            text-align: left;
        }
        table.data-table th { background-color: #f1f5f9; color: #334155; font-weight: bold; }
        table.data-table tr:nth-child(even) { background-color: #f8fafc; }

        .page-break { page-break-before: always; }
        .footer { position: fixed; bottom: -10px; width: 100%; text-align: center; font-size: 10px; color: #94a3b8; }
    </style>
</head>
<body>

    <div class="footer">
        Generated by ICT Ticketing System | {{ now()->format('Y') }}
    </div>

    <div class="header">
        <table class="header-table">
            <tr>
                <td>
                    <h1>ICT Monthly Complaint Report</h1>
                    <div class="meta-data">Reporting Period: <strong>{{ $targetDate->format('F Y') }}</strong></div>
                </td>
                <td style="text-align: right;">
                    <div class="meta-data">Generated On: <strong>{{ now()->format('d M Y, h:i A') }}</strong></div>
                    <div class="meta-data">Department: IT Support</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="summary-container">
        <tr>
            <td class="summary-card">
                <div class="label">Total Tickets</div>
                <div class="value">{{ $stats['total'] }}</div>
            </td>
            <td class="summary-card open">
                <div class="label">Open</div>
                <div class="value">{{ $stats['open'] }}</div>
            </td>
            <td class="summary-card assigned">
                <div class="label">Assigned</div>
                <div class="value">{{ $stats['assigned'] }}</div>
            </td>
            <td class="summary-card">
                <div class="label">On Hold</div>
                <div class="value">{{ $stats['on_hold'] }}</div>
            </td>
            <td class="summary-card resolved">
                <div class="label">Resolved</div>
                <div class="value">{{ $stats['resolved'] }}</div>
            </td>
        </tr>
    </table>

    <div class="charts-container">
        <img src="{{ $imageData }}" class="charts-image" alt="Charts">
    </div>

    <div class="page-break"></div>

    <div class="header" style="margin-top: 20px;">
        <table class="header-table">
            <tr>
                <td>
                    <h1>Detailed Ticket Log</h1>
                    <div class="meta-data">Reporting Period: {{ $targetDate->format('F Y') }}</div>
                </td>
            </tr>
        </table>
    </div>

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Reporter</th>
                <th>Issue</th>
                <th>Category</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($monthlyTickets as $ticket)
            <tr>
                <td>#{{ $ticket->id }}</td>
                <td>{{ $ticket->reporter_name }}</td>
                <td>{{ $ticket->title }}</td>
                <td>{{ $ticket->category }}</td>
                <td>{{ $ticket->priority }}</td>
                <td>{{ $ticket->status }}</td>
                <td>{{ $ticket->created_at->format('d/m/Y') }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center;">No tickets recorded for this month.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
